In [1]:
import scipy.io as sio
import numpy as np
import pandas as pd
import datetime
import matplotlib as mpl
import tkinter
mpl.use('TkAgg')
import matplotlib.pyplot as plt
plt.ion()
# If using tkinter ('TkAgg') then make font color black,
mpl.rcParams.update({'text.color': 'k'})
mpl.rcParams.update({'axes.labelcolor': 'k'})
mpl.rcParams.update({'xtick.color': 'k'})
mpl.rcParams.update({'ytick.color': 'k'})
#import sciencedates #same as igrf12fort
import spacepy.time as spt
#import xarray as xr #same as igrf12fort and sciencedates
mpl.rcParams.update({'font.size': 15})
mpl.rcParams.update({'figure.figsize' : [10.0, 8.0]})


# file = '/SPENCEdata/Research/Satellites/FAST/espec_identification/20181009-Kalle_inds_21-24MLT__BOTH__gigante_DB.sav'

# redMagFile = '/SPENCEdata/Research/Satellites/FAST/espec_identification/20181009-Kalle_inds_21-24MLT__BOTH__gigante_DB__MAG_coords.sav'

# allFile='/SPENCEdata/Research/Satellites/FAST/espec_identification/20181009-Kalle_inds_21-24MLT__BOTH__gigante_DB__delta_t_and_mag_coords.sav'
allFile='/SPENCEdata/Research/Satellites/FAST/espec_identification/20181010-Kalle_inds_ALLMLT__BOTH__gigante_DB__delta_t_and_mag_coords.sav'

# this = sio.readsav(file,python_dict=True)
# thisMAG = sio.readsav(redMagFile,python_dict=True)
all = sio.readsav(allFile,python_dict=True)

This unreleased version of SpacePy is not supported by the SpacePy team.


In [2]:
print(all.keys())
# print(thisMAG.keys())
espec = all['espec']
mag = all['mag']
dts = all['espec_delta_t']

dict_keys(['espec', 'good_i', 'espec_delta_t', 'mag'])


In [3]:
print(espec.dtype)
print(mag.dtype)
print(dts.dtype)
espec.x[0].shape
# espec.mono[0].shape
# espec.broad[0].shape
# print(dat.alt[0].shape)
# print(dat.lon[0].shape)
#print(dat.lat[0].shape)

(numpy.record, [(('x', 'X'), 'O'), (('orbit', 'ORBIT'), 'O'), (('mlt', 'MLT'), 'O'), (('ilat', 'ILAT'), 'O'), (('alt', 'ALT'), 'O'), (('mono', 'MONO'), 'O'), (('broad', 'BROAD'), 'O'), (('diffuse', 'DIFFUSE'), 'O'), (('je', 'JE'), 'O'), (('jee', 'JEE'), 'O'), (('nbad_espec', 'NBAD_ESPEC'), 'O'), (('mapfactor', 'MAPFACTOR'), 'O'), (('chare', 'CHARE'), 'O'), (('info', 'INFO'), 'O')])
(numpy.record, [(('alt', 'ALT'), 'O'), (('lon', 'LON'), 'O'), (('lat', 'LAT'), 'O')])
>f4


(39642712,)

In [4]:
# Get a datetime from our UTC doubles created by IDL
datetime.datetime.utcfromtimestamp(espec.x[0][-1])


datetime.datetime(2002, 10, 25, 0, 13, 21, 111771)

In [5]:
# Diffusers
# diff_i=np.where(espec.diffuse[0] == 1)
# print(diff_i)

# Uvver fings
# print(np.where((espec.mono[0] == 1) | (espec.mono[0] == 2))[0].shape)
# print(np.where(espec.diffuse[0] == 1)[0].shape)

In [6]:
fig1 = plt.figure(num=1,figsize=(20, 8))
ax = fig1.add_subplot(111)
plt.hist(mag.lon[0])
plt.show()


(array([3557430., 3602612., 3293638., 4477242., 4968136., 4863028.,
        4492572., 3375921., 3532358., 3479775.]),
 array([1.83011161e-06, 3.59999962e+01, 7.19999924e+01, 1.07999985e+02,
        1.43999969e+02, 1.79999969e+02, 2.15999969e+02, 2.51999954e+02,
        2.87999939e+02, 3.23999939e+02, 3.59999939e+02], dtype=float32),
 <a list of 10 Patch objects>)

In [29]:
# Nå bare de som ligger innimellom 0–6 MLT
postmid_i=np.where((espec.mlt[0] >= 0) & (espec.mlt[0] <= 6))
magLonPost = mag.lon[0][postmid_i]
magLatPost = mag.lat[0][postmid_i]
dtsPost = dts[postmid_i]
jePost = espec.je[0][postmid_i]
jeePost = espec.jee[0][postmid_i]

premid_i=np.where((espec.mlt[0] >= 21) & (espec.mlt[0] <= 24))
magLonPre = mag.lon[0][premid_i]
magLatPre = mag.lat[0][premid_i]
dtsPre = dts[premid_i]
jePre = espec.je[0][premid_i]
jeePre = espec.jee[0][premid_i]


In [30]:
postmid_i[0].shape
premid_i[0].shape

(10157872,)

(5282108,)

In [31]:
# mag.lon[0][postmid_i]
# fig1 = plt.figure(num=1,figsize=(20, 8))
# ax1 = fig1.add_subplot(121)
fig1, (ax1, ax2) = plt.subplots(1, 2,figsize=(20, 8))
ax1.set_title("0-6 MLT")
ax1.set_xlabel("MAG Longitude")
ax1.hist(magLonPost)
# ax2 = fig1.add_subplot(122)
ax2.set_title("21-24 MLT")
ax2.set_xlabel("MAG Longitude")
ax2.hist(magLonPre)
plt.show()

Text(0.5,1,'0-6 MLT')

Text(0.5,0,'MAG Longitude')

(array([ 984437.,  905406.,  835951., 1123102., 1274816., 1242960.,
        1099577.,  837636.,  906898.,  947089.]),
 array([5.3781869e-06, 3.5999996e+01, 7.1999985e+01, 1.0799998e+02,
        1.4399997e+02, 1.7999995e+02, 2.1599995e+02, 2.5199994e+02,
        2.8799994e+02, 3.2399991e+02, 3.5999991e+02], dtype=float32),
 <a list of 10 Patch objects>)

Text(0.5,1,'21-24 MLT')

Text(0.5,0,'MAG Longitude')

(array([511765., 472458., 456909., 592003., 586312., 610051., 591650.,
        499634., 482845., 478481.]),
 array([7.3907075e-05, 3.6000057e+01, 7.2000038e+01, 1.0800002e+02,
        1.4400002e+02, 1.7999998e+02, 2.1599997e+02, 2.5199995e+02,
        2.8799994e+02, 3.2399994e+02, 3.5999991e+02], dtype=float32),
 <a list of 10 Patch objects>)

In [32]:
# Nå skaper vi vektene for den 2D matrise 
# Et histogram skal være det som gjelder bare tid
# det andre skal være det vektete flukser
#lonKanter=np.
lonKanter=np.arange(0,360,30)
latKanter=(np.arange(0,85,5)+100)/2.
latKanterSH=(np.arange(-60,25,5)-120)/2.
latKanterAll=(np.arange(-60,305,5)-120)/2.
print(lonKanter)
print(latKanter)
print(latKanterSH)
print(latKanterAll)

[  0  30  60  90 120 150 180 210 240 270 300 330]
[50.  52.5 55.  57.5 60.  62.5 65.  67.5 70.  72.5 75.  77.5 80.  82.5
 85.  87.5 90. ]
[-90.  -87.5 -85.  -82.5 -80.  -77.5 -75.  -72.5 -70.  -67.5 -65.  -62.5
 -60.  -57.5 -55.  -52.5 -50. ]
[-90.  -87.5 -85.  -82.5 -80.  -77.5 -75.  -72.5 -70.  -67.5 -65.  -62.5
 -60.  -57.5 -55.  -52.5 -50.  -47.5 -45.  -42.5 -40.  -37.5 -35.  -32.5
 -30.  -27.5 -25.  -22.5 -20.  -17.5 -15.  -12.5 -10.   -7.5  -5.   -2.5
   0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5  25.   27.5
  30.   32.5  35.   37.5  40.   42.5  45.   47.5  50.   52.5  55.   57.5
  60.   62.5  65.   67.5  70.   72.5  75.   77.5  80.   82.5  85.   87.5
  90. ]


In [77]:
hist2DTidPost,xEdgePost,yEdgePost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanter),weights=dtsPost)
hist2DJePost,xEdgePost,yEdgePost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanter),weights=dtsPost*jePost)
hist2DJeePost,xEdgePost,yEdgePost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanter),weights=dtsPost*jeePost)

hist2DTidSHPost,xEdgeSHPost,yEdgeSHPost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanterSH),weights=dtsPost)
hist2DJeSHPost,xEdgeSHPost,yEdgeSHPost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanterSH),weights=dtsPost*jePost)
hist2DJeeSHPost,xEdgeSHPost,yEdgeSHPost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanterSH),weights=dtsPost*jeePost)

hist2DTidAllPost,xEdgeAllPost,yEdgeAllPost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanterAll),weights=dtsPost)
hist2DJeAllPost,xEdgeAllPost,yEdgeAllPost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanterAll),weights=dtsPost*jePost)
hist2DJeeAllPost,xEdgeAllPost,yEdgeAllPost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanterAll),weights=dtsPost*jeePost)
hist2DNAllPost,xEdgeAllPost,yEdgeAllPost=np.histogram2d(magLonPost,magLatPost,bins=(lonKanter,latKanterAll))

In [78]:
histDivJePost = hist2DJePost*0.
histDivJeePost = hist2DJeePost*0.
nzIndsPost = np.where(hist2DTidPost > 0)
histDivJePost[nzIndsPost] = hist2DJePost[nzIndsPost]/hist2DTidPost[nzIndsPost]
histDivJeePost[nzIndsPost] = hist2DJeePost[nzIndsPost]/hist2DTidPost[nzIndsPost]

histDivJeSHPost = hist2DJeSHPost*0.
histDivJeeSHPost = hist2DJeeSHPost*0.
nzIndsSHPost = np.where(hist2DTidSHPost > 0)
histDivJeSHPost[nzIndsSHPost] = hist2DJeSHPost[nzIndsSHPost]/hist2DTidSHPost[nzIndsSHPost]
histDivJeeSHPost[nzIndsSHPost] = hist2DJeeSHPost[nzIndsSHPost]/hist2DTidSHPost[nzIndsSHPost]

histDivJeAllPost = hist2DJeAllPost*0.
histDivJeeAllPost = hist2DJeeAllPost*0.
nzIndsAllPost = np.where(hist2DTidAllPost > 0)
histDivJeAllPost[nzIndsAllPost] = hist2DJeAllPost[nzIndsAllPost]/hist2DTidAllPost[nzIndsAllPost]
histDivJeeAllPost[nzIndsAllPost] = hist2DJeeAllPost[nzIndsAllPost]/hist2DTidAllPost[nzIndsAllPost]

In [38]:
print(histDivJePost.shape)
print(xEdgePost.shape)
print(yEdgePost.shape)
print(xEdgePost[0],xEdgePost[-1])

(11, 16)
(12,)
(17,)
0 330


In [41]:
fig2 = plt.figure(num=2,figsize=(20, 8))
ax = fig2.add_subplot(131)
ax.set_title('imshow: equidistant')
im = plt.imshow(histDivJePost.T, interpolation='nearest', origin='low',
                extent=[xEdgePost[0], xEdgePost[-1], yEdgePost[0], yEdgePost[-1]])
ax2 = fig2.add_subplot(132)
ax2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgePost, yEdgePost)
ax2.pcolormesh(X, Y, histDivJePost.T)
ax2.set_aspect('auto')
# plt.show()
ax3 = fig2.add_subplot(133)
ax3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(ax3, interpolation='bilinear',
                                extent=[xEdgePost[0], xEdgePost[-1], yEdgePost[0], yEdgePost[-1]])
xcenters = xEdgePost[:-1] + 0.5 * (xEdgePost[1:] - xEdgePost[:-1])
ycenters = yEdgePost[:-1] + 0.5 * (yEdgePost[1:] - yEdgePost[:-1])
im3.set_data(xcenters, ycenters, histDivJePost.T)
ax3.images.append(im3)
ax3.set_xlim(xEdgePost[0], xEdgePost[-1])
ax3.set_ylim(yEdgePost[0], yEdgePost[-1])
ax3.set_aspect('auto')
# fig2.colorbar(im3, ax=ax3)
plt.show()

Text(0.5,1,'imshow: equidistant')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(50.0, 90.0)

In [42]:
fig2 = plt.figure(num=2,figsize=(20, 8))
ax = fig2.add_subplot(131)
ax.set_title('imshow: equidistant')
im = plt.imshow(histDivJePost.T, interpolation='nearest', origin='low',
                extent=[xEdgePost[0], xEdgePost[-1], yEdgePost[0], yEdgePost[-1]])
ax2 = fig2.add_subplot(132)
ax2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgePost, yEdgePost)
ax2.pcolormesh(X, Y, histDivJePost.T)
ax2.set_aspect('auto')
# plt.show()
ax3 = fig2.add_subplot(133)
ax3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(ax3, interpolation='bilinear',
                                extent=[xEdgePost[0], xEdgePost[-1], yEdgePost[0], yEdgePost[-1]])
xcenters = xEdgePost[:-1] + 0.5 * (xEdgePost[1:] - xEdgePost[:-1])
ycenters = yEdgePost[:-1] + 0.5 * (yEdgePost[1:] - yEdgePost[:-1])
im3.set_data(xcenters, ycenters, histDivJePost.T)
ax3.images.append(im3)
ax3.set_xlim(xEdgePost[0], xEdgePost[-1])
ax3.set_ylim(yEdgePost[0], yEdgePost[-1])
ax3.set_aspect('auto')
# fig2.colorbar(im3, ax=ax3)
plt.show()

Text(0.5,1,'imshow: equidistant')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(50.0, 90.0)

In [43]:
figSHPost = plt.figure(num=3,figsize=(20, 8))
axSHPost = figSHPost.add_subplot(131)
axSHPost.set_title('imshow: equidistant')
im = plt.imshow(histDivJeSHPost.T, interpolation='nearest', origin='low',
                extent=[xEdgeSHPost[0], xEdgeSHPost[-1], yEdgeSHPost[0], yEdgeSHPost[-1]])

axSHPost2 = figSHPost.add_subplot(132)
axSHPost2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgeSHPost, yEdgeSHPost)
axSHPost2.pcolormesh(X, Y, histDivJeSHPost.T)
axSHPost2.set_aspect('auto')
# plt.show()
axSHPost3 = figSHPost.add_subplot(133)
axSHPost3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(axSHPost3, interpolation='bilinear',
                                extent=[xEdgeSHPost[0], xEdgeSHPost[-1], yEdgeSHPost[0], yEdgeSHPost[-1]])
xcenters = xEdgeSHPost[:-1] + 0.5 * (xEdgeSHPost[1:] - xEdgeSHPost[:-1])
ycenters = yEdgeSHPost[:-1] + 0.5 * (yEdgeSHPost[1:] - yEdgeSHPost[:-1])
im3.set_data(xcenters, ycenters, histDivJeSHPost.T)
axSHPost3.images.append(im3)
axSHPost3.set_xlim(xEdgeSHPost[0], xEdgeSHPost[-1])
axSHPost3.set_ylim(yEdgeSHPost[0], yEdgeSHPost[-1])
axSHPost3.set_aspect('auto')
plt.show()

Text(0.5,1,'imshow: equidistant')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(-90.0, -50.0)

In [83]:
figAllPost = plt.figure(num=4,figsize=(16, 8))
figAllPost.suptitle("0-6 MLT")
# axAllPost = figAllPost.add_subplot(131)
# axAllPost.set_title('imshow: equidistant')
# im = plt.imshow(histDivJeAllPost.T, interpolation='nearest', origin='low',
#                 extent=[xEdgeAllPost[0], xEdgeAllPost[-1], yEdgeAllPost[0], yEdgeAllPost[-1]])

axAllPost2 = figAllPost.add_subplot(121)
axAllPost2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgeAllPost, yEdgeAllPost)
axAllPost2.pcolormesh(X, Y, histDivJeAllPost.T)
axAllPost2.set_aspect('auto')
# plt.show()
axAllPost3 = figAllPost.add_subplot(122)
axAllPost3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(axAllPost3, interpolation='bilinear',
                                extent=[xEdgeAllPost[0], xEdgeAllPost[-1], yEdgeAllPost[0], yEdgeAllPost[-1]])
xcenters = xEdgeAllPost[:-1] + 0.5 * (xEdgeAllPost[1:] - xEdgeAllPost[:-1])
ycenters = yEdgeAllPost[:-1] + 0.5 * (yEdgeAllPost[1:] - yEdgeAllPost[:-1])
im3.set_data(xcenters, ycenters, histDivJeAllPost.T)
axAllPost3.images.append(im3)
axAllPost3.set_xlim(xEdgeAllPost[0], xEdgeAllPost[-1])
axAllPost3.set_ylim(yEdgeAllPost[0], yEdgeAllPost[-1])
axAllPost3.set_aspect('auto')
cbAllPost=figAllPost.colorbar(im3, ax=axAllPost3)
cbAllPost.set_label("# cm^-2 s^-1")
plt.show()

Text(0.5,0.98,'0-6 MLT')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(-90.0, 90.0)

In [84]:
figAllPost2 = plt.figure(num=5,figsize=(16, 8))
figAllPost2.suptitle("0-6 MLT")
# axAllPost = figAllPost.add_subplot(131)
# axAllPost.set_title('imshow: equidistant')
# im = plt.imshow(hist2DNAllPost.T, interpolation='nearest', origin='low',
#                 extent=[xEdgeAllPost[0], xEdgeAllPost[-1], yEdgeAllPost[0], yEdgeAllPost[-1]])

axAllPost2 = figAllPost2.add_subplot(121)
axAllPost2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgeAllPost, yEdgeAllPost)
axAllPost2.pcolormesh(X, Y, hist2DNAllPost.T)
axAllPost2.set_aspect('auto')
# plt.show()
axAllPost3 = figAllPost2.add_subplot(122)
axAllPost3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(axAllPost3, interpolation='bilinear',
                                extent=[xEdgeAllPost[0], xEdgeAllPost[-1], yEdgeAllPost[0], yEdgeAllPost[-1]])
xcenters = xEdgeAllPost[:-1] + 0.5 * (xEdgeAllPost[1:] - xEdgeAllPost[:-1])
ycenters = yEdgeAllPost[:-1] + 0.5 * (yEdgeAllPost[1:] - yEdgeAllPost[:-1])
im3.set_data(xcenters, ycenters, hist2DNAllPost.T)
axAllPost3.images.append(im3)
axAllPost3.set_xlim(xEdgeAllPost[0], xEdgeAllPost[-1])
axAllPost3.set_ylim(yEdgeAllPost[0], yEdgeAllPost[-1])
axAllPost3.set_aspect('auto')
cbAllPost2=figAllPost2.colorbar(im3, ax=axAllPost3)
cbAllPost2.set_label("N")
plt.show()

Text(0.5,0.98,'0-6 MLT')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(-90.0, 90.0)

In [85]:
figAllPost3 = plt.figure(num=6,figsize=(16, 8))
figAllPost3.suptitle("0-6 MLT")
# axAllPost = figAllPost3.add_subplot(131)
# axAllPost.set_title('imshow: equidistant')
# im = plt.imshow(histDivJeeAllPost.T, interpolation='nearest', origin='low',
#                 extent=[xEdgeAllPost[0], xEdgeAllPost[-1], yEdgeAllPost[0], yEdgeAllPost[-1]])

axAllPost2 = figAllPost3.add_subplot(121)
axAllPost2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgeAllPost, yEdgeAllPost)
axAllPost2.pcolormesh(X, Y, histDivJeeAllPost.T)
axAllPost2.set_aspect('auto')
# plt.show()
axAllPost3 = figAllPost3.add_subplot(122)
axAllPost3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(axAllPost3, interpolation='bilinear',
                                extent=[xEdgeAllPost[0], xEdgeAllPost[-1], yEdgeAllPost[0], yEdgeAllPost[-1]])
xcenters = xEdgeAllPost[:-1] + 0.5 * (xEdgeAllPost[1:] - xEdgeAllPost[:-1])
ycenters = yEdgeAllPost[:-1] + 0.5 * (yEdgeAllPost[1:] - yEdgeAllPost[:-1])
im3.set_data(xcenters, ycenters, histDivJeeAllPost.T)
axAllPost3.images.append(im3)
axAllPost3.set_xlim(xEdgeAllPost[0], xEdgeAllPost[-1])
axAllPost3.set_ylim(yEdgeAllPost[0], yEdgeAllPost[-1])
axAllPost3.set_aspect('auto')
cbAllPost=figAllPost3.colorbar(im3, ax=axAllPost3)
cbAllPost.set_label("mW m^-2")
plt.show()

Text(0.5,0.98,'0-6 MLT')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(-90.0, 90.0)

In [80]:
hist2DTidPre,xEdgePre,yEdgePre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanter),weights=dtsPre)
hist2DJePre,xEdgePre,yEdgePre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanter),weights=dtsPre*jePre)
hist2DJeePre,xEdgePre,yEdgePre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanter),weights=dtsPre*jeePre)

hist2DTidSHPre,xEdgeSHPre,yEdgeSHPre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanterSH),weights=dtsPre)
hist2DJeSHPre,xEdgeSHPre,yEdgeSHPre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanterSH),weights=dtsPre*jePre)
hist2DJeeSHPre,xEdgeSHPre,yEdgeSHPre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanterSH),weights=dtsPre*jeePre)

hist2DTidAllPre,xEdgeAllPre,yEdgeAllPre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanterAll),weights=dtsPre)
hist2DJeAllPre,xEdgeAllPre,yEdgeAllPre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanterAll),weights=dtsPre*jePre)
hist2DJeeAllPre,xEdgeAllPre,yEdgeAllPre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanterAll),weights=dtsPre*jeePre)
hist2DNAllPre,xEdgeAllPre,yEdgeAllPre=np.histogram2d(magLonPre,magLatPre,bins=(lonKanter,latKanterAll))

In [81]:
histDivJePre = hist2DJePre*0.
histDivJeePre = hist2DJeePre*0.
nzIndsPre = np.where(hist2DTidPre > 0)
histDivJePre[nzIndsPre] = hist2DJePre[nzIndsPre]/hist2DTidPre[nzIndsPre]
histDivJeePre[nzIndsPre] = hist2DJeePre[nzIndsPre]/hist2DTidPre[nzIndsPre]

histDivJeSHPre = hist2DJeSHPre*0.
histDivJeeSHPre = hist2DJeeSHPre*0.
nzIndsSHPre = np.where(hist2DTidSHPre > 0)
histDivJeSHPre[nzIndsSHPre] = hist2DJeSHPre[nzIndsSHPre]/hist2DTidSHPre[nzIndsSHPre]
histDivJeeSHPre[nzIndsSHPre] = hist2DJeeSHPre[nzIndsSHPre]/hist2DTidSHPre[nzIndsSHPre]

histDivJeAllPre = hist2DJeAllPre*0.
histDivJeeAllPre = hist2DJeeAllPre*0.
nzIndsAllPre = np.where(hist2DTidAllPre > 0)
histDivJeAllPre[nzIndsAllPre] = hist2DJeAllPre[nzIndsAllPre]/hist2DTidAllPre[nzIndsAllPre]
histDivJeeAllPre[nzIndsAllPre] = hist2DJeeAllPre[nzIndsAllPre]/hist2DTidAllPre[nzIndsAllPre]

In [49]:
fig2Pre = plt.figure(num=7,figsize=(20, 8))
ax = fig2Pre.add_subplot(131)
ax.set_title('imshow: equidistant')
im = plt.imshow(histDivJePre.T, interpolation='nearest', origin='low',
                extent=[xEdgePre[0], xEdgePre[-1], yEdgePre[0], yEdgePre[-1]])
ax2 = fig2Pre.add_subplot(132)
ax2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgePre, yEdgePre)
ax2.pcolormesh(X, Y, histDivJePre.T)
ax2.set_aspect('auto')
# plt.show()
ax3 = fig2Pre.add_subplot(133)
ax3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(ax3, interpolation='bilinear',
                                extent=[xEdgePre[0], xEdgePre[-1], yEdgePre[0], yEdgePre[-1]])
xcenters = xEdgePre[:-1] + 0.5 * (xEdgePre[1:] - xEdgePre[:-1])
ycenters = yEdgePre[:-1] + 0.5 * (yEdgePre[1:] - yEdgePre[:-1])
im3.set_data(xcenters, ycenters, histDivJePre.T)
ax3.images.append(im3)
ax3.set_xlim(xEdgePre[0], xEdgePre[-1])
ax3.set_ylim(yEdgePre[0], yEdgePre[-1])
ax3.set_aspect('auto')
# fig2Pre.colorbar(im3, ax=ax3)
plt.show()

Text(0.5,1,'imshow: equidistant')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(50.0, 90.0)

In [56]:
figSHPre = plt.figure(num=8,figsize=(20, 8))
figSHPre.suptitle("21-24 MLT")
axSHPre = figSHPre.add_subplot(131)
axSHPre.set_title('imshow: equidistant')
im = plt.imshow(histDivJeSHPre.T, interpolation='nearest', origin='low',
                extent=[xEdgeSHPre[0], xEdgeSHPre[-1], yEdgeSHPre[0], yEdgeSHPre[-1]])

axSHPre2 = figSHPre.add_subplot(132)
axSHPre2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgeSHPre, yEdgeSHPre)
axSHPre2.pcolormesh(X, Y, histDivJeSHPre.T)
axSHPre2.set_aspect('auto')
# plt.show()
axSHPre3 = figSHPre.add_subplot(133)
axSHPre3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(axSHPre3, interpolation='bilinear',
                                extent=[xEdgeSHPre[0], xEdgeSHPre[-1], yEdgeSHPre[0], yEdgeSHPre[-1]])
xcenters = xEdgeSHPre[:-1] + 0.5 * (xEdgeSHPre[1:] - xEdgeSHPre[:-1])
ycenters = yEdgeSHPre[:-1] + 0.5 * (yEdgeSHPre[1:] - yEdgeSHPre[:-1])
im3.set_data(xcenters, ycenters, histDivJeSHPre.T)
axSHPre3.images.append(im3)
axSHPre3.set_xlim(xEdgeSHPre[0], xEdgeSHPre[-1])
axSHPre3.set_ylim(yEdgeSHPre[0], yEdgeSHPre[-1])
axSHPre3.set_aspect('auto')
plt.show()

Text(0.5,0.98,'21-24 MLT')

Text(0.5,1,'imshow: equidistant')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(-90.0, -50.0)

In [57]:
figAllPre = plt.figure(num=9,figsize=(16, 8))
figAllPre.suptitle("21-24 MLT")
# axAllPre = figAllPre.add_subplot(131)
# axAllPre.set_title('imshow: equidistant')
# im = plt.imshow(histDivJeAllPre.T, interpolation='nearest', origin='low',
#                 extent=[xEdgeAllPre[0], xEdgeAllPre[-1], yEdgeAllPre[0], yEdgeAllPre[-1]])

axAllPre2 = figAllPre.add_subplot(121)
axAllPre2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgeAllPre, yEdgeAllPre)
axAllPre2.pcolormesh(X, Y, histDivJeAllPre.T)
axAllPre2.set_aspect('auto')
# plt.show()
axAllPre3 = figAllPre.add_subplot(122)
axAllPre3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(axAllPre3, interpolation='bilinear',
                                extent=[xEdgeAllPre[0], xEdgeAllPre[-1], yEdgeAllPre[0], yEdgeAllPre[-1]])
xcenters = xEdgeAllPre[:-1] + 0.5 * (xEdgeAllPre[1:] - xEdgeAllPre[:-1])
ycenters = yEdgeAllPre[:-1] + 0.5 * (yEdgeAllPre[1:] - yEdgeAllPre[:-1])
im3.set_data(xcenters, ycenters, histDivJeAllPre.T)
axAllPre3.images.append(im3)
axAllPre3.set_xlim(xEdgeAllPre[0], xEdgeAllPre[-1])
axAllPre3.set_ylim(yEdgeAllPre[0], yEdgeAllPre[-1])
axAllPre3.set_aspect('auto')
figAllPre.colorbar(im3, ax=axAllPre3)
plt.show()

Text(0.5,0.98,'21-24 MLT')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(-90.0, 90.0)

In [86]:
figAllPre = plt.figure(num=10,figsize=(16, 8))
figAllPre.suptitle("21-24 MLT")
# axAllPre = figAllPre.add_subplot(131)
# axAllPre.set_title('imshow: equidistant')
# im = plt.imshow(histDivJeAllPre.T, interpolation='nearest', origin='low',
#                 extent=[xEdgeAllPre[0], xEdgeAllPre[-1], yEdgeAllPre[0], yEdgeAllPre[-1]])

axAllPre2 = figAllPre.add_subplot(121)
axAllPre2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgeAllPre, yEdgeAllPre)
axAllPre2.pcolormesh(X, Y, histDivJeAllPre.T)
axAllPre2.set_aspect('auto')
# plt.show()
axAllPre3 = figAllPre.add_subplot(122)
axAllPre3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(axAllPre3, interpolation='bilinear',
                                extent=[xEdgeAllPre[0], xEdgeAllPre[-1], yEdgeAllPre[0], yEdgeAllPre[-1]])
xcenters = xEdgeAllPre[:-1] + 0.5 * (xEdgeAllPre[1:] - xEdgeAllPre[:-1])
ycenters = yEdgeAllPre[:-1] + 0.5 * (yEdgeAllPre[1:] - yEdgeAllPre[:-1])
im3.set_data(xcenters, ycenters, histDivJeAllPre.T)
axAllPre3.images.append(im3)
axAllPre3.set_xlim(xEdgeAllPre[0], xEdgeAllPre[-1])
axAllPre3.set_ylim(yEdgeAllPre[0], yEdgeAllPre[-1])
axAllPre3.set_aspect('auto')
cbAllPre=figAllPre.colorbar(im3, ax=axAllPre3)
cbAllPre.set_label("# cm^-2 s^-1")
plt.show()

Text(0.5,0.98,'21-24 MLT')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(-90.0, 90.0)

In [87]:
figAllPre2 = plt.figure(num=11,figsize=(16, 8))
figAllPre2.suptitle("21-24 MLT")
# axAllPre = figAllPre.add_subplot(131)
# axAllPre.set_title('imshow: equidistant')
# im = plt.imshow(hist2DNAllPre.T, interpolation='nearest', origin='low',
#                 extent=[xEdgeAllPre[0], xEdgeAllPre[-1], yEdgeAllPre[0], yEdgeAllPre[-1]])

axAllPre2 = figAllPre2.add_subplot(121)
axAllPre2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgeAllPre, yEdgeAllPre)
axAllPre2.pcolormesh(X, Y, hist2DNAllPre.T)
axAllPre2.set_aspect('auto')
# plt.show()
axAllPre3 = figAllPre2.add_subplot(122)
axAllPre3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(axAllPre3, interpolation='bilinear',
                                extent=[xEdgeAllPre[0], xEdgeAllPre[-1], yEdgeAllPre[0], yEdgeAllPre[-1]])
xcenters = xEdgeAllPre[:-1] + 0.5 * (xEdgeAllPre[1:] - xEdgeAllPre[:-1])
ycenters = yEdgeAllPre[:-1] + 0.5 * (yEdgeAllPre[1:] - yEdgeAllPre[:-1])
im3.set_data(xcenters, ycenters, hist2DNAllPre.T)
axAllPre3.images.append(im3)
axAllPre3.set_xlim(xEdgeAllPre[0], xEdgeAllPre[-1])
axAllPre3.set_ylim(yEdgeAllPre[0], yEdgeAllPre[-1])
axAllPre3.set_aspect('auto')
cbAllPre2=figAllPre2.colorbar(im3, ax=axAllPre3)
cbAllPre2.set_label("N")
plt.show()

Text(0.5,0.98,'21-24 MLT')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(-90.0, 90.0)

In [88]:
figAllPre3 = plt.figure(num=12,figsize=(16, 8))
figAllPre3.suptitle("21-24 MLT")
# axAllPre = figAllPre3.add_subplot(131)
# axAllPre.set_title('imshow: equidistant')
# im = plt.imshow(histDivJeAllPre.T, interpolation='nearest', origin='low',
#                 extent=[xEdgeAllPre[0], xEdgeAllPre[-1], yEdgeAllPre[0], yEdgeAllPre[-1]])

axAllPre2 = figAllPre3.add_subplot(121)
axAllPre2.set_title('pcolormesh: exact bin edges')
X, Y = np.meshgrid(xEdgeAllPre, yEdgeAllPre)
axAllPre2.pcolormesh(X, Y, histDivJeeAllPre.T)
axAllPre2.set_aspect('auto')
# plt.show()
axAllPre3 = figAllPre3.add_subplot(122)
axAllPre3.set_title('NonUniformImage: interpolated')
im3 = mpl.image.NonUniformImage(axAllPre3, interpolation='bilinear',
                                extent=[xEdgeAllPre[0], xEdgeAllPre[-1], yEdgeAllPre[0], yEdgeAllPre[-1]])
xcenters = xEdgeAllPre[:-1] + 0.5 * (xEdgeAllPre[1:] - xEdgeAllPre[:-1])
ycenters = yEdgeAllPre[:-1] + 0.5 * (yEdgeAllPre[1:] - yEdgeAllPre[:-1])
im3.set_data(xcenters, ycenters, histDivJeeAllPre.T)
axAllPre3.images.append(im3)
axAllPre3.set_xlim(xEdgeAllPre[0], xEdgeAllPre[-1])
axAllPre3.set_ylim(yEdgeAllPre[0], yEdgeAllPre[-1])
axAllPre3.set_aspect('auto')
cbAllPre=figAllPre3.colorbar(im3, ax=axAllPre3)
cbAllPre.set_label("mW m^-2")
plt.show()

Text(0.5,0.98,'21-24 MLT')

Text(0.5,1,'pcolormesh: exact bin edges')

Text(0.5,1,'NonUniformImage: interpolated')

(0, 330)

(-90.0, 90.0)